package com.dixit.video.downloader

import android.content.Intent
import android.os.Bundle
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.app.AlertDialog
import java.io.File

class PlaylistActivity:AppCompatActivity(){
    private val prefs by lazy{getSharedPreferences("dvd_playlist",MODE_PRIVATE)}
    private lateinit var files:List<File>
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(DvdUi.bg);setPadding(DvdUi.dp(this@PlaylistActivity,12),0,DvdUi.dp(this@PlaylistActivity,12),DvdUi.dp(this@PlaylistActivity,12))};val head=DvdUi.row(this);head.addView(DvdUi.text(this,"‹",34f).apply{setOnClickListener{finish()}},LinearLayout.LayoutParams(DvdUi.dp(this,42),DvdUi.dp(this,54)));head.addView(LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(DvdUi.text(this@PlaylistActivity,"Playlists",20f,DvdUi.text,true));addView(DvdUi.text(this@PlaylistActivity,"Create • organize • play",11f,DvdUi.secondary))},LinearLayout.LayoutParams(0,-2,1f));val create=Button(this).apply{text="+ Create Playlist";textSize=10f;backgroundTintList=android.content.res.ColorStateList.valueOf(DvdUi.brand);setTextColor(DvdUi.text)};head.addView(create,LinearLayout.LayoutParams(-2,DvdUi.dp(this,42)));root.addView(head)
        val cards=DvdUi.row(this);arrayOf("★ Favorites\n0 items","Chill Vibes\n18 items","Travel\n12 items").forEach{t->val v=DvdUi.text(this,t,11f,DvdUi.text,true).apply{setPadding(DvdUi.dp(this@PlaylistActivity,12),DvdUi.dp(this@PlaylistActivity,12),DvdUi.dp(this@PlaylistActivity,12),DvdUi.dp(this@PlaylistActivity,12));background=DvdUi.background(DvdUi.card,16,DvdUi.divider)};cards.addView(v,LinearLayout.LayoutParams(0,DvdUi.dp(this,72),1f).apply{marginEnd=DvdUi.dp(this@PlaylistActivity,5)})};root.addView(cards)
        val play=Button(this).apply{text="▶  Play selected";textSize=12f;backgroundTintList=android.content.res.ColorStateList.valueOf(DvdUi.brand);setTextColor(DvdUi.text)};root.addView(play,LinearLayout.LayoutParams(-1,DvdUi.dp(this,50)).apply{topMargin=DvdUi.dp(this@PlaylistActivity,10)})
        val list=ListView(this).apply{choiceMode=ListView.CHOICE_MODE_MULTIPLE;divider=null;dividerHeight=DvdUi.dp(this@PlaylistActivity,8)};val dir=getExternalFilesDir(android.os.Environment.DIRECTORY_DOWNLOADS);files=dir?.listFiles()?.filter{it.isFile&&!it.name.endsWith(".part")}.orEmpty().sortedByDescending{it.lastModified()};val selected=prefs.getStringSet("items",emptySet())!!.toMutableSet();list.adapter=ArrayAdapter(this,android.R.layout.simple_list_item_multiple_choice,files.map{it.name});files.forEachIndexed{i,f->if(selected.contains(f.absolutePath))list.setItemChecked(i,true)};root.addView(list,LinearLayout.LayoutParams(-1,0,1f));play.setOnClickListener{val chosen=files.filterIndexed{i,_->list.isItemChecked(i)};if(chosen.isEmpty()){Toast.makeText(this,"Select media first",Toast.LENGTH_SHORT).show();return@setOnClickListener};prefs.edit().putStringSet("items",chosen.map{it.absolutePath}.toSet()).apply();startActivity(Intent(this,PlayerActivity::class.java).putExtra("playlist",chosen.map{it.absolutePath}.toTypedArray()).putExtra("url",chosen.first().absolutePath))};create.setOnClickListener{val e=EditText(this).apply{hint="Playlist name"};AlertDialog.Builder(this).setTitle("Create playlist").setView(e).setPositiveButton("Create"){_,_->Toast.makeText(this,"Playlist '${e.text}' created",Toast.LENGTH_SHORT).show()}.setNegativeButton("Cancel",null).show()};setContentView(root)}
}
