package com.dixit.video.downloader

import android.content.res.ColorStateList
import android.os.Bundle
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity

class SettingsActivity:AppCompatActivity(){
    private val prefs by lazy{getSharedPreferences("dvd_settings",MODE_PRIVATE)}
    private fun save(key:String,value:Any){prefs.edit().apply{when(value){is Boolean->putBoolean(key,value);is Int->putInt(key,value);is String->putString(key,value)}}.apply()}
    private fun section(root:LinearLayout,title:String,subtitle:String){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;padding(14);background=DvdUi.background(DvdUi.card,18,DvdUi.divider)};box.addView(DvdUi.text(this,title,15f,DvdUi.text,true));box.addView(DvdUi.text(this,subtitle,10f,DvdUi.secondary).apply{setPadding(0,DvdUi.dp(this@SettingsActivity,3),0,0)});root.addView(box,LinearLayout.LayoutParams(-1,-2).apply{topMargin=DvdUi.dp(this@SettingsActivity,10)})}
    private fun LinearLayout.padding(v:Int){setPadding(DvdUi.dp(this@SettingsActivity,v),DvdUi.dp(this@SettingsActivity,v),DvdUi.dp(this@SettingsActivity,v),DvdUi.dp(this@SettingsActivity,v))}
    private fun sw(root:LinearLayout,label:String,key:String,def:Boolean){val row=DvdUi.row(this);row.setPadding(DvdUi.dp(this,10),DvdUi.dp(this,9),DvdUi.dp(this,4),DvdUi.dp(this,9));row.addView(DvdUi.text(this,label,12f,DvdUi.text),LinearLayout.LayoutParams(0,-2,1f));val s=Switch(this).apply{isChecked=prefs.getBoolean(key,def);buttonTintList=ColorStateList.valueOf(DvdUi.brand);setOnCheckedChangeListener{_,v->save(key,v)}};row.addView(s);root.addView(row)}
    private fun spinner(root:LinearLayout,label:String,key:String,values:Array<String>,index:Int){val row=DvdUi.row(this);row.setPadding(DvdUi.dp(this,10),DvdUi.dp(this,6),DvdUi.dp(this,4),DvdUi.dp(this,6));row.addView(DvdUi.text(this,label,12f,DvdUi.text),LinearLayout.LayoutParams(0,-2,1f));val s=Spinner(this);s.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,values);s.setSelection(prefs.getInt(key,index).coerceIn(0,values.lastIndex));s.setOnItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onNothingSelected(p:AdapterView<*>?){};override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){save(key,pos)}};row.addView(s,LinearLayout.LayoutParams(DvdUi.dp(this,150),-2));root.addView(row)}
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);val scroll=ScrollView(this);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(DvdUi.bg);padding(12)};val head=DvdUi.row(this);head.addView(DvdUi.text(this,"‹",34f).apply{setOnClickListener{finish()}},LinearLayout.LayoutParams(DvdUi.dp(this,42),DvdUi.dp(this,54)));head.addView(LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;addView(DvdUi.text(this@SettingsActivity,"Settings",20f,DvdUi.text,true));addView(DvdUi.text(this@SettingsActivity,"Appearance • downloads • playback",11f,DvdUi.secondary))},LinearLayout.LayoutParams(0,-2,1f));root.addView(head)
        section(root,"Appearance","Make the downloader feel like the reference design")
        spinner(root,"Theme","theme",arrayOf("Dark","System","Light"),0);spinner(root,"Accent","accent",arrayOf("Purple / Blue","Cyan","Violet"),0);sw(root,"Compact download cards","compact_cards",false)
        section(root,"Download Settings","Quality, format, queue and reliability")
        sw(root,"Wi‑Fi only","wifi_only",false);sw(root,"Automatic retry","auto_retry",true);sw(root,"Scan completed media into library","scan_media",true);spinner(root,"Maximum simultaneous downloads","concurrency",arrayOf("1","2","3","4"),0);spinner(root,"Maximum automatic retries","max_retries",arrayOf("1","2","3","4","5"),2);spinner(root,"Default quality","default_quality",arrayOf("Best available","8K","4K","2K","1080p","720p","480p","360p","Audio only"),0);spinner(root,"Preferred format","preferred_format",arrayOf("Auto","MP4","WebM","MKV","M4A","MP3","Opus"),0);spinner(root,"Smart download mode","smart_mode",arrayOf("Best available","Best compatibility","Data saver","Audio only","Video only"),0);spinner(root,"Preferred FPS","preferred_fps",arrayOf("Auto","24","30","60","120"),0);spinner(root,"Video codec","video_codec",arrayOf("Auto","H.264","H.265/HEVC","VP9","AV1"),0);spinner(root,"Audio codec","audio_codec",arrayOf("Auto","AAC","Opus","MP3"),0);spinner(root,"Video bitrate","video_bitrate",arrayOf("Auto","500 kbps","1 Mbps","2 Mbps","4 Mbps","8 Mbps","12 Mbps"),0);spinner(root,"Audio bitrate","audio_bitrate",arrayOf("Auto","64 kbps","96 kbps","128 kbps","192 kbps","256 kbps","320 kbps"),0);spinner(root,"Duplicate files","duplicate_policy",arrayOf("Rename automatically","Skip if already exists","Replace existing"),0);spinner(root,"Download speed limit","speed_limit_kbps",arrayOf("Unlimited","256 KB/s","512 KB/s","1 MB/s","2 MB/s","5 MB/s"),0)
        section(root,"Player Settings","Controls shown in the advanced player")
        sw(root,"Remember playback position","remember_position",true);sw(root,"Auto picture-in-picture","auto_pip",true);sw(root,"Hardware acceleration","hardware_acceleration",true);spinner(root,"Decoder preference","decoder",arrayOf("Auto","Hardware preferred","Software / FFmpeg preferred"),0);spinner(root,"Seek step","seek_seconds",arrayOf("5 seconds","10 seconds","15 seconds","30 seconds","60 seconds"),1);spinner(root,"Loop mode","loop",arrayOf("Off","Repeat one","Repeat all"),0);spinner(root,"Volume boost","volume_boost",arrayOf("100%","125%","150%","175%","200%"),0)
        section(root,"Library & Storage","Folders, filters and media management")
        sw(root,"Show hidden/system media","show_hidden",false);sw(root,"Auto-add downloads to Library","auto_library",true);sw(root,"Remember favorites and watched state","remember_library_state",true)
        root.addView(DvdUi.text(this,"No login • No advertising • No subscription • No API/token requirement\nDRM, authentication and protected-stream bypass are not supported.",10f,DvdUi.secondary).apply{setPadding(DvdUi.dp(this@SettingsActivity,8),DvdUi.dp(this@SettingsActivity,18),DvdUi.dp(this@SettingsActivity,8),DvdUi.dp(this@SettingsActivity,22))})
        scroll.addView(root);setContentView(scroll)}
}
